Class {
	#name : 'PharoCommonSettingsUpTo11',
	#superclass : 'PharoAbstractSettings',
	#category : 'PharoSettingsUpTo11',
	#package : 'PharoSettingsUpTo11'
}

{ #category : 'class initialization' }
PharoCommonSettingsUpTo11 class >> enableFluidClassDefinition [

	<script>
	ClassDefinitionPrinter showFluidClassDefinition: true
]

{ #category : 'class initialization' }
PharoCommonSettingsUpTo11 class >> initialize [

	self enableFluidClassDefinition
]

{ #category : 'see class side' }
PharoCommonSettingsUpTo11 >> seeClassSide [ 
]
