Class {
	#name : 'PharoCommonSettingsUpTo12',
	#superclass : 'PharoAbstractSettings',
	#category : 'PharoSettingsUpTo12',
	#package : 'PharoSettingsUpTo12'
}

{ #category : 'class initialization' }
PharoCommonSettingsUpTo12 class >> initialize [

	self setAuthorName
]

{ #category : 'class initialization' }
PharoCommonSettingsUpTo12 class >> setAuthorName [

	<script>
	Author fullName: 'CyrilFerlicot'
]

{ #category : 'see class side' }
PharoCommonSettingsUpTo12 >> seeClassSide [

]
